package my.vaadin.app;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainScreen extends VerticalLayout {
	protected AbsoluteLayout mainPanel;
	protected TextField includeTextField;
	protected TextField excludeTextField;
	protected Button includeButton;
	protected Button excludeButton;
	protected Panel excludePanel;
	protected CssLayout excludeLayout;
	protected AbsoluteLayout checkBoxLayout;
	protected TextField cuisine;
	protected CheckBox americanCheckBox;
	protected CheckBox europeanCheckBox;
	protected CheckBox asianCheckBox;
	protected CheckBox easyCheckBox;
	protected CheckBox capableCooksCheckBox;
	protected CheckBox superEasyCheckBox;
	protected CheckBox advancedCheckBox;
	protected CheckBox challengingCheckBox;
	protected Panel includePanel;
	protected CssLayout includeLayout;
	protected Panel recepesPanel;
	protected CssLayout recipesLayout;
	protected TextField searchTextField;
	protected Button searchButton;
	protected Button randomRecipe;

	public MainScreen() {
		Design.read(this);
	}
}
